### ISSUE TITLE
fengqianan申请加入组织

### ISSUE THREAD

**Issue by fengqianan** [leetcode-notebook/leetcode-notebook.github.io#10]
- 使用语言：C++
- 个人介绍：接触C++不久，希望通过leetcode刷题提高自己的C++理解深度和编程能力，希望能得到team内大佬的指点。

**Comment by JalanJiang** [comment]
你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

扫描二维码入群~我们将在群中推送题目

![3681578365465_ pic](https://user-images.githubusercontent.com/7787716/71864748-9f14e680-313b-11ea-8145-afa0fb23866f.jpg)
