### ISSUE TITLE
申请

### ISSUE THREAD

**Issue by guozijia26** [leetcode-notebook/leetcode-notebook.github.io#18]
- 使用语言：中文
- 个人介绍：目前是研究生在读，想加入刷题小组，相互督促学习，为今年秋招做准备

**Comment by JalanJiang** [comment]
语言指的是编程语言哈

----

你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

扫描二维码入群，我们将在群中推送题目。入群后请查看群公告修改群名片，并进行简单的自我介绍，让大家认识你呀~

![61579673739_ pic](https://user-images.githubusercontent.com/7787716/72869935-b221dc00-3d21-11ea-8846-93603a1215f2.jpg)

----

完成以下任务后请手动关闭此 Issue：

- [ ] 确认邀请邮件并通过此邮件加入组织
- [ ] 扫码加入算法群
