### ISSUE TITLE
申请加入组织

### ISSUE THREAD

**Issue by yongliRUC** [leetcode-notebook/leetcode-notebook.github.io#2]
- 使用语言：java
- 个人介绍：是一名学生，正准备刷题找工作。

**Comment by JalanJiang** [comment]
你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

加我微信 `jvilla1994`，备注「算法」，拉你进算法群。我们将在群中推送题目。

当然，如果你有足够的自制力，你也可以自己选题自己完成！

## 关于总结

每周的周期为周一至周日，每周日组织将根据 Commit 对上周完成的题量做一次统计，以可视化的方式进行展示，作为一种监督方式。
