### ISSUE TITLE
Join!

### ISSUE THREAD

**Issue by Maplesotrys** [leetcode-notebook/leetcode-notebook.github.io#20]
- 使用语言：python
- 个人介绍：想变强的小学渣一枚

**Comment by JalanJiang** [comment]
你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

扫描二维码入群，我们将在群中推送题目。入群后请查看群公告修改群名片，并进行简单的自我介绍，让大家认识你呀~

![251580439609_ pic](https://user-images.githubusercontent.com/7787716/73509071-e3349780-4418-11ea-83fc-a7f1c2e97855.jpg)
