### ISSUE TITLE
渴望与各位大佬一起变得更强

### ISSUE THREAD

**Issue by amituofo1996** [leetcode-notebook/leetcode-notebook.github.io#23]
- 使用语言：C语言
- 个人介绍：末流211本+20准研究生

**Comment by JalanJiang** [comment]
你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

扫描二维码入群，我们将在群中推送题目。入群后请查看群公告修改群名片，并进行简单的自我介绍，让大家认识你呀~

![251580439609_ pic](https://user-images.githubusercontent.com/7787716/73509071-e3349780-4418-11ea-83fc-a7f1c2e97855.jpg)

----

确认完成以下事项后请自行关闭 Issue：

- [ ] 在邮箱确认邀请邮件
- [ ] 加入配题群
- [ ] 修改群昵称为「使用语言 + 酷炫昵称」

**Comment by amituofo1996** [comment]
thanks a lot!


 
---原始邮件---
发件人: "江不知"<notifications@github.com&gt;
发送时间: 2020年2月5日 11:38:00
收件人: "leetcode-notebook/leetcode-notebook.github.io"<leetcode-notebook.github.io@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"amituofo1996"<497121896@qq.com&gt;;
主题: Re: [leetcode-notebook/leetcode-notebook.github.io] 渴望与各位大佬一起变得更强 (#23)



你好~欢迎加入刷题小组！👏👏👏
 
已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。
 
加入组织后，以你的名字在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。
 
关于配题
 
扫描二维码入群，我们将在群中推送题目。入群后请查看群公告修改群名片，并进行简单的自我介绍，让大家认识你呀~
 

 
 
确认完成以下事项后请自行关闭 Issue：
  
 在邮箱确认邀请邮件 

 加入配题群 

 修改群昵称为「使用语言 + 酷炫昵称」

**Comment by amituofo1996** [comment]
您好，我太久没登github，您有时间可以再发一下二维码给我吗，非常感谢

**Comment by JalanJiang** [comment]
![221582179904_ pic](https://user-images.githubusercontent.com/7787716/74906722-caeae380-53ec-11ea-8dba-2389a99e5e03.jpg)

**Comment by amituofo1996** [comment]
您好，我的微信是 tianlongcheng ，可以方便拉我一下吗

**Comment by amituofo1996** [comment]
我还是看不到您发的图片啊

**Comment by JalanJiang** [comment]
好的， 我这边拉你。

**Comment by JalanJiang** [comment]
> tianlongcheng

不能通过微信号查到你，你可以加我 jvilla1994
