### ISSUE TITLE
申请加入组织

### ISSUE THREAD

**Issue by lixuchen123** [leetcode-notebook/leetcode-notebook.github.io#37]
- 使用语言：C language
- 个人介绍：硕士  毕业于吉林大学 现在上海华为担任嵌入式软件工程师  刷刷Leetcode， 希望多向大神请教学习。

**Comment by JalanJiang** [comment]
你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

扫描二维码入群，我们将在群中推送题目。入群后请查看群公告修改群名片，并进行简单的自我介绍，让大家认识你呀~

![361583657189_ pic](https://user-images.githubusercontent.com/7787716/76159518-6c4b9680-615c-11ea-9cc3-bbbcc495a4cc.jpg)

----

确认完成以下事项后请自行关闭 Issue：

- [ ] 在邮箱确认邀请邮件
- [ ] 加入配题群
- [ ] 修改群昵称为「使用语言 + 酷炫昵称」
