### ISSUE TITLE
申请加入刷题小组

### ISSUE THREAD

**Issue by xiaoxiaoshiliu** [leetcode-notebook/leetcode-notebook.github.io#4]
- 使用语言：c++
- 个人介绍：研二一枚，热爱算法，但是编程思路比较不灵活，希望可以刷leetcode来提升自己写代码的思路。加深对算法及数据结构的理解。

**Comment by JalanJiang** [comment]
你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

扫描二维码入群~我们将在群中推送题目。

![3161576034691_ pic](https://user-images.githubusercontent.com/7787716/70588810-e9707980-1c08-11ea-8c7a-b0940dccd4b2.jpg)

当然，如果你有足够的自制力，你也可以自己选题自己完成！
