### ISSUE TITLE
leetcode-python

### ISSUE THREAD

**Issue by napxie** [leetcode-notebook/leetcode-notebook.github.io#8]
- 使用语言：python, java
- 个人介绍：

**Comment by JalanJiang** [comment]
你好~欢迎加入刷题小组！👏👏👏

已邀请你加入组织，请注意邀请邮件。如果想在你的名片中显示组织头像，你可以进入 People 标签，找到你自己，将 Private 点击修改为 Public。

加入组织后，以**你的名字**在组织中创建一个仓库，你可以用你喜欢的任何方式组织仓库内容。

## 关于配题

扫描二维码入群~我们将在群中推送题目。

![image](https://user-images.githubusercontent.com/7787716/71457608-a81bc480-27d9-11ea-91d3-6e3f1e395b8b.png)
